project:
  type: book
  output-dir: docs

book:
  title: "Notas de teoría - Cálculo I"

  chapters:
    - index.qmd
    - cap1.qmd
    - cap2.qmd
    - cap3.qmd
    - cap4.qmd
    - cap5.qmd
    - cap6.qmd

format:
  html:
    toc: true
    toc-title: "Contenidos"
    toc-depth: 3
    number-sections: false